SmartMach/webapp-v1

app/Views/Production_Downtime.php, assets/js/settings_machine_validation.js
1. Machine Brand Name lowercase issue
2. Future Shift Hiding
3. Downtime graph plotting for intermediate graph plotting
=> 3 Bug Updated

app/Models/PDM_Model.php, app/Views/Production_Corrections.php, app/Views/Production_Downtime.php, app/Views/Production_Rejection.php, app/Views/Settings_Goals_Others.php, app/Views/Settings_Machines.php, app/Views/Settings_Tools.php, app/Views/Settings_Users.php
preloader and event preventdefault and correction mincount changes
=> 67 duplicate record created

app/Views/Financial_FOeeDrillDown.php, app/Views/Grafana_Home.php, app/Views/Production_Downtime.php, app/Views/Settings_Users.php, assets/css/main.css
financial oee drill down not shown for site user
if i select tool then automatically selected the all parts in dropdown
access control save button
=> 80 financial oee drill down not shown for site user

app/Controllers/Financial_Metrics.php, app/Models/Financial_Model.php
1. No data and Offline data filter in Financial Metrics
2. Record split in Financial Metrics calculation
3. TEEP value miscalculated
=> No Data and Offline Data, Duration split and TEEP

app/Controllers/Financial_Metrics.php
Issue in find the Part-wise Downtime vs speed loss
=> Performance Calculation changed

app/Config/App.php, app/Views/Daily_Production_Status.php, app/Views/Financial_OpportunityInsights.php, app/Views/Settings_Goals_Others.php
fourth module error msg  and ui corrections opportunity insights
=> fourth module error msg  and ui corrections opportunity insights

app/Controllers/PDM_controller.php, app/Models/PDM_Model.php, app/Views/Production_Downtime.php
Toolchangeover graph issue fixing
=> Toolchangeover graph issue fixing

app/Controllers/Daily_production_controller.php, app/Models/Daily_production_Model.php, app/Views/Daily_Production_Status.php
target formula all time formula adding
=> target formula all time formula adding

app/Controllers/Daily_production_controller.php, app/Models/Daily_production_Model.php, app/Views/Daily_Production_Status.php, app/Views/Settings_Users.php
target formula and preloader every 5minutes
=> target formula and preloader every 5minutes

app/Views/Production_Rejection.php
quality rejection error handling
=> quality rejection error handling

app/Controllers/Financial_Metrics.php, app/Views/Production_Rejection.php
quality rejections module error handling
=> quality rejections module error handling

app/Views/Grafana_Home.php, app/Views/User_Login.php
webpage title and title image adding
=> webpage title and title image adding

app/Views/Production_Rejection.php
multiple error messages in rejection
=> multiple error messages

app/Config/App.php, app/Views/Production_Downtime.php
Bulk edit notes edit after update refresh the div
=> Bulk edit notes edit after update refresh the div

app/Config/App.php, app/Controllers/PDM_controller.php, app/Views/Production_Downtime.php
bulk edit notes after update refresh the div
=> bulk edit notes after update refresh the div

app/Models/PDM_Model.php, app/Views/Financial_FOeeDrillDown.php, app/Views/Grafana_Home.php, app/Views/Quality_Production.php
1. Font awesome icons local
2. Production Quality - Graph color
3. Side Nav bar icons
4. Shift date enable in downtime
5. From time and To time Financial Metrics
=> Demo Server Bug

app/Views/Downtime_Production.php, app/Views/Oee_Drill_Down.php, assets/js/Downtime_Production.js
production downtime and oee drilldown module dropdwon closing work
=> production downtime and oee drilldown module dropdwon closing work

app/Config/App.php, app/Views/Current_Shift_Performance.php
current shift performance oui screen downtime value
=> current shift performance oui screen downtime value

app/Views/Alert_Settings.php, app/Views/Daily_Production_Status.php, app/Views/Downtime_Production.php, app/Views/Oee_Drill_Down.php, app/Views/Quality_Production.php, assets/css/Downtime_production.css, assets/css/oee_drill_down.css, assets/js/Downtime_Production.js
oee drildown over all target graph hovering production downtime dropdown double line solving
=> oee drildown over all target graph hovering production downtime dropdown double line solving

app/Controllers/Current_Shift_Performance.php, app/Controllers/Daily_production_controller.php, app/Controllers/OEE_Drill_Down_controller.php, app/Controllers/Production_Downtime_controller.php, app/Controllers/Production_Quality.php, app/Models/Current_Shift_Performance_Model.php, app/Models/Production_Downtime_Model.php, app/Views/Alert_Settings.php, app/Views/Current_Shift_Performance.php, app/Views/Downtime_Production.php, app/Views/Financial_FOeeDrillDown.php, app/Views/Financial_OpportunityInsights.php, app/Views/Oee_Drill_Down.php, app/Views/Quality_Production.php, app/Views/Work_Order_Management.php, assets/css/Downtime_production.css, assets/css/alert_settings.css, assets/css/oee_drill_down.css, assets/js/Downtime_Production.js
All module loader and some internal and external bugs cleared to move on development merge
=> All module loader and some internal and external bugs cleared to move on development merge 

app/Config/Logger.php, app/Controllers/Current_Shift_Performance.php, app/Controllers/Daily_production_controller.php, app/Controllers/Financial_Metrics.php, app/Controllers/OEE_Drill_Down_controller.php, app/Controllers/Production_Downtime_controller.php, app/Controllers/Production_Quality.php, app/Models/Daily_production_Model.php, app/Models/Production_Quality_Model.php, app/Views/Alert_Settings.php, app/Views/Current_Shift_Performance.php, app/Views/Daily_Production_Status.php, app/Views/Oee_Drill_Down.php, app/Views/Quality_Production.php, app/Views/Work_Order_Management.php, assets/css/oui_current_shift_performance.css
all output modules logger file creation for every day and loader and some ui bugs fixed
=> all output modules logger file creation for every day and loader and some ui bugs fixed 

app/Config/App.php, app/Controllers/Current_Shift_Performance.php, app/Models/Current_Shift_Performance_Model.php, app/Views/Alert_Settings.php, app/Views/Current_Shift_Performance.php, app/Views/Financial_FOeeDrillDown.php, app/Views/Grafana_Home.php, app/Views/Header.php, app/Views/Production_Corrections.php, app/Views/Production_Downtime.php, app/Views/Production_Rejection.php, app/Views/Settings_Machines.php, app/Views/Settings_Tools.php, app/Views/Settings_Users.php, app/Views/User_Login.php, app/Views/Work_Order_Management.php, assets/css/Downtime_production.css, assets/css/alert_settings.css, assets/css/config.css, assets/css/css_general.css, assets/css/login.css, assets/css/main.css, assets/css/standard/config.css, assets/css/standard/layout.css, assets/css/standard/template.css, assets/css/styles_production_quality.css
all ui and functional bugs updated
=> All module bugs 2023 06 27

app/Controllers/Current_Shift_Performance.php, app/Controllers/Daily_production_controller.php, app/Controllers/PDM_controller.php, app/Models/Current_Shift_Performance_Model.php, app/Models/Daily_production_Model.php, app/Models/PDM_Model.php, app/Views/Current_Shift_Performance.php, app/Views/Daily_Production_Status.php, app/Views/Financial_FOeeDrillDown.php, app/Views/Financial_OpportunityInsights.php, app/Views/Grafana_Home.php, app/Views/Production_Downtime.php, app/Views/Settings_Users.php
finall updated code in before client meet with 2023-09-08
=> Default site working

app/Views/Work_Order_Management.php
Issue No: 8 and 11 has been cleared
=> Jira Issue SMAC-24

app/Views/Quality_Production.php
1. Quality Production - Multiple check box issues cleared.
2. Multiple check box standard code implemented for COPQ graph
=> SMAC - 59 Ticket issue cleared

app/Views/Quality_Production.php
1. UI correction has been solved
=> SMAC - 61 Ticket issue solved

app/Views/Work_Order_Management.php
=> SMAC -  71 Ticket issue cleared

app/Views/Financial_FOeeDrillDown.php
=> SMAC - 44 Ticket issue cleared

app/Models/Operator_model.php, app/Views/Current_Shift_Performance.php
2023 10 30 bugs fixing Current shift performance parts missing issue cleared
=>  2023 10 30 bugs fixing Current shift performance parts missing issue cleared

app/Views/Downtime_Production.php, assets/css/Downtime_production.css, assets/js/Downtime_Production.js
2023 11 01 bugs fixing production downtime dropdown filter double click issue cleared
=> 2023 11 01 bugs fixing production downtime dropdown filter double click issue cleared

app/Views/Current_Shift_Performance.php, app/Views/Downtime_Production.php, assets/css/Downtime_production.css, assets/js/Downtime_Production.js
=> Development merge

app/Views/Current_Shift_Performance.php, app/Views/Downtime_Production.php, assets/css/Downtime_production.css, assets/js/Downtime_Production.js
Development merge production downtime dropdown filter double click issue cleared
=> Development merge production downtime dropdown filter double click issue cleared

app/Views/Alert_Settings.php, app/Views/Oee_Drill_Down.php, assets/css/alert_settings.css, assets/css/oee_drill_down.css, assets/js/alert_settings.js, assets/js/oee_drill_down.js
alert management and oee drill down module graph filter dropdown and table filter dropdown double click issue cleared
=> alert management and oee drill down module graph filter dropdown and table filter dropdown double click issue cleared

app/Views/Alert_Settings.php, app/Views/Financial_FOeeDrillDown.php, app/Views/Oee_Drill_Down.php, app/Views/Production_Downtime.php, assets/js/Downtime_Production.js, assets/js/alert_settings.js
financial oee drilldown from date to date current hour its showing the issue is cleared
=> financial oee drilldown from date to date current hour its showing the issue is cleared

app/Views/Downtime_Production.php, assets/css/Downtime_production.css
prodcution downtime module notes hovering table alignment mismatched
=> prodcution downtime module notes hovering table alignment mismatched

app/Views/Downtime_Production.php
2023 11 07 bugs fixing production downtime hovering taggle remove in notes
=> 2023 11 07 bugs fixing production downtime hovering taggle remove in notes

app/Views/Downtime_Production.php, app/Views/Settings_Users.php
wrong sitename showing on user account edit user details issue cleared
=> wrong sitename showing on user account edit user details issue cleared
